### ISSUE TITLE
[FEATURE] Adapt design of page module to 7LTS new backend styles

### ISSUE THREAD

**Issue by jpmschuler** [jpmschuler/templavoilaplus#1]
Idea is to harmonise the design between the modules. Copying design from TYPO3 core page module a bit and adapting colouring and spacing.
Especially removing floats and font-size declarations from old 6LTS-templavoila-CSS file.

**Comment by opi99** [comment]
Hi,

this looks already very nice. But, for merging the issue needs to be created in pluspol-interactive/templavoilaplus and the Line in the commit message reads "Resolves: #issuenumber"

Greetings Alex

**Comment by jpmschuler** [comment]
pulled in https://github.com/pluspol-interactive/templavoilaplus/pull/61
